[package]
name = "sendgrid-amqp-bridge"
version = "0.1.0"
authors = ["Otavio Salvador <otavio@ossystems.com.br>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
exitfailure = "0.5"
slog = "2"
slog-async = "2"
slog-term = "2"
structopt = "0.2"
